name: Deploy login.petflow.pro

on:
  push:
    branches:
      - main   # Ajuste se usar outro branch

jobs:
  deploy-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy login.petflow.pro to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/pineapplelab/login.petflow.pro
            git pull
            docker-compose restart nginx_login
